version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Using Node.js version:"
      - node -v
      - echo "Installing pnpm"
      - npm install -g pnpm
      - echo "Installing dependencies"
      - pnpm install
      - echo "Adding Tailwind, PostCSS, Autoprefixer (if not already in package.json)"
      - pnpm add -D tailwindcss postcss autoprefixer
      - npx tailwindcss init -p
      - echo "Ensuring React 18 is installed"
      - pnpm add react@18 react-dom@18

  pre_build:
    commands:
      - echo "Cleaning old artifacts"
      - rm -rf build
      - echo "Validating dependencies"
      - pnpm install

  build:
    commands:
      - echo "Building React app"
      - pnpm run build

artifacts:
  files:
    - '**/*'
  base-directory: dist
